import { describe, expect, it } from 'vitest';

import { SecondBrainService } from '../src/services/second-brain.service.js';

describe('second brain service', () => {
  it('creates entries, normalizes tags, and filters by query and tag', () => {
    const service = new SecondBrainService();

    const first = service.createEntry('student-1', {
      title: 'Federalism Notes',
      content: 'Link fiscal federalism with cooperative governance.',
      tags: ['polity', ' governance ', 'polity', ''],
      importance: 'high',
    });

    service.createEntry('student-1', {
      title: 'Climate Policy',
      content: 'Carbon markets and adaptation finance.',
      tags: ['environment', 'economy'],
    });

    expect(first.tags).toEqual(['polity', 'governance']);
    expect(service.listEntries('student-1', { q: 'federalism' })).toHaveLength(1);
    expect(service.listEntries('student-1', { tag: 'environment' })).toHaveLength(1);
  });

  it('builds tag connections and returns insight fallback for empty users', () => {
    const service = new SecondBrainService();
    service.createEntry('student-1', {
      title: 'Entry One',
      content: 'A',
      tags: ['polity', 'economy', 'history'],
    });
    service.createEntry('student-1', {
      title: 'Entry Two',
      content: 'B',
      tags: ['polity', 'economy'],
    });

    const connections = service.getConnections('student-1');
    expect(connections[0]).toEqual(
      expect.objectContaining({
        fromTag: 'economy',
        toTag: 'polity',
        strength: 2,
      }),
    );

    const fallback = service.getAutoGeneratedInsights('new-user');
    expect(fallback).toHaveLength(1);
    expect(fallback[0].relatedTags).toEqual([]);
  });

  it('prevents cross-user updates and deletes', () => {
    const service = new SecondBrainService();
    const entry = service.createEntry('student-1', {
      title: 'Private',
      content: 'Only mine',
    });

    expect(() => service.updateEntry('student-2', entry.id, { title: 'Hack' })).toThrow('not found');
    expect(() => service.deleteEntry('student-2', entry.id)).toThrow('not found');
  });
});
