import { randomUUID } from 'crypto';

import { AppError } from '../errors/app-error.js';

type ImportanceLevel = 'low' | 'medium' | 'high';

type SecondBrainEntry = {
  id: string;
  userId: string;
  title: string;
  content: string;
  tags: string[];
  importance: ImportanceLevel;
  source: 'manual' | 'auto';
  createdAt: Date;
  updatedAt: Date;
};

type CreateSecondBrainEntryInput = {
  title: string;
  content: string;
  tags?: string[];
  importance?: ImportanceLevel;
};

type UpdateSecondBrainEntryInput = {
  title?: string;
  content?: string;
  tags?: string[];
  importance?: ImportanceLevel;
};

type ListSecondBrainEntriesQuery = {
  q?: string;
  tag?: string;
};

type SecondBrainConnection = {
  fromTag: string;
  toTag: string;
  strength: number;
  entryIds: string[];
};

const normalizeTags = (tags: string[] = []): string[] => {
  return [...new Set(tags.map((tag) => tag.trim()).filter((tag) => tag.length > 0))];
};

export class SecondBrainService {
  private readonly entries = new Map<string, SecondBrainEntry>();

  listEntries(userId: string, query: ListSecondBrainEntriesQuery = {}): SecondBrainEntry[] {
    const normalizedQ = query.q?.trim().toLowerCase();
    const normalizedTag = query.tag?.trim().toLowerCase();

    return [...this.entries.values()]
      .filter((entry) => entry.userId === userId)
      .filter((entry) => {
        if (!normalizedTag) {
          return true;
        }
        return entry.tags.some((tag) => tag.toLowerCase() === normalizedTag);
      })
      .filter((entry) => {
        if (!normalizedQ) {
          return true;
        }
        return (
          entry.title.toLowerCase().includes(normalizedQ) ||
          entry.content.toLowerCase().includes(normalizedQ) ||
          entry.tags.some((tag) => tag.toLowerCase().includes(normalizedQ))
        );
      })
      .sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime());
  }

  createEntry(userId: string, input: CreateSecondBrainEntryInput): SecondBrainEntry {
    const now = new Date();
    const entry: SecondBrainEntry = {
      id: randomUUID(),
      userId,
      title: input.title,
      content: input.content,
      tags: normalizeTags(input.tags),
      importance: input.importance ?? 'medium',
      source: 'manual',
      createdAt: now,
      updatedAt: now,
    };

    this.entries.set(entry.id, entry);
    return entry;
  }

  updateEntry(userId: string, entryId: string, input: UpdateSecondBrainEntryInput): SecondBrainEntry {
    const existing = this.entries.get(entryId);
    if (!existing || existing.userId !== userId) {
      throw new AppError('Second brain entry not found', 404);
    }

    const updated: SecondBrainEntry = {
      ...existing,
      title: input.title ?? existing.title,
      content: input.content ?? existing.content,
      tags: input.tags ? normalizeTags(input.tags) : existing.tags,
      importance: input.importance ?? existing.importance,
      updatedAt: new Date(),
    };

    this.entries.set(updated.id, updated);
    return updated;
  }

  deleteEntry(userId: string, entryId: string): void {
    const existing = this.entries.get(entryId);
    if (!existing || existing.userId !== userId) {
      throw new AppError('Second brain entry not found', 404);
    }

    this.entries.delete(entryId);
  }

  getConnections(userId: string): SecondBrainConnection[] {
    const userEntries = this.listEntries(userId);
    const connectionMap = new Map<string, SecondBrainConnection>();

    for (const entry of userEntries) {
      if (entry.tags.length < 2) {
        continue;
      }

      for (let i = 0; i < entry.tags.length; i += 1) {
        for (let j = i + 1; j < entry.tags.length; j += 1) {
          const [fromTag, toTag] = [entry.tags[i], entry.tags[j]].sort();
          const key = `${fromTag}::${toTag}`;
          const existing = connectionMap.get(key);
          if (existing) {
            existing.strength += 1;
            existing.entryIds.push(entry.id);
          } else {
            connectionMap.set(key, {
              fromTag,
              toTag,
              strength: 1,
              entryIds: [entry.id],
            });
          }
        }
      }
    }

    return [...connectionMap.values()].sort((a, b) => b.strength - a.strength);
  }

  getAutoGeneratedInsights(userId: string): Array<{ id: string; insight: string; relatedTags: string[] }> {
    const userEntries = this.listEntries(userId);
    const connections = this.getConnections(userId).slice(0, 5);

    if (connections.length === 0 && userEntries.length === 0) {
      return [
        {
          id: randomUUID(),
          insight: 'Start adding entries to unlock cross-topic insight suggestions.',
          relatedTags: [],
        },
      ];
    }

    return connections.map((connection) => ({
      id: randomUUID(),
      insight: `Frequent link observed: ${connection.fromTag} ↔ ${connection.toTag}. Build one integrated revision note for this pair.`,
      relatedTags: [connection.fromTag, connection.toTag],
    }));
  }
}

export const createSecondBrainService = (): SecondBrainService => new SecondBrainService();

export type {
  CreateSecondBrainEntryInput,
  ListSecondBrainEntriesQuery,
  SecondBrainConnection,
  SecondBrainEntry,
  UpdateSecondBrainEntryInput,
};
