import type { NextFunction, Request, Response } from 'express';
import { Router } from 'express';

import { authMiddleware } from '../middleware/auth.middleware.js';
import { authRateLimiter } from '../middleware/rate-limit.middleware.js';
import { validateRequest } from '../middleware/request-validation.js';
import {
  createSecondBrainEntrySchema,
  deleteSecondBrainEntrySchema,
  listSecondBrainEntriesSchema,
  updateSecondBrainEntrySchema,
} from '../schemas/second-brain.schema.js';
import { createSecondBrainService, type SecondBrainService } from '../services/second-brain.service.js';

const asyncHandler =
  (handler: (req: Request, res: Response, next: NextFunction) => Promise<void>) =>
  (req: Request, res: Response, next: NextFunction): void => {
    void handler(req, res, next).catch(next);
  };

type CreateSecondBrainRouterOptions = {
  secondBrainService?: SecondBrainService;
};

export const createSecondBrainRouter = (options: CreateSecondBrainRouterOptions = {}): Router => {
  const router = Router();
  const secondBrainService = options.secondBrainService ?? createSecondBrainService();

  router.get(
    '/second-brain/entries',
    authRateLimiter,
    authMiddleware,
    validateRequest(listSecondBrainEntriesSchema),
    asyncHandler(async (req, res) => {
      res.status(200).json(secondBrainService.listEntries(req.authUser!.userId, req.query));
    }),
  );

  router.post(
    '/second-brain/entries',
    authRateLimiter,
    authMiddleware,
    validateRequest(createSecondBrainEntrySchema),
    asyncHandler(async (req, res) => {
      res.status(201).json(secondBrainService.createEntry(req.authUser!.userId, req.body));
    }),
  );

  router.put(
    '/second-brain/entries/:id',
    authRateLimiter,
    authMiddleware,
    validateRequest(updateSecondBrainEntrySchema),
    asyncHandler(async (req, res) => {
      res.status(200).json(secondBrainService.updateEntry(req.authUser!.userId, req.params.id, req.body));
    }),
  );

  router.delete(
    '/second-brain/entries/:id',
    authRateLimiter,
    authMiddleware,
    validateRequest(deleteSecondBrainEntrySchema),
    asyncHandler(async (req, res) => {
      secondBrainService.deleteEntry(req.authUser!.userId, req.params.id);
      res.status(204).send();
    }),
  );

  router.get(
    '/second-brain/connections',
    authRateLimiter,
    authMiddleware,
    asyncHandler(async (req, res) => {
      res.status(200).json(secondBrainService.getConnections(req.authUser!.userId));
    }),
  );

  router.get(
    '/second-brain/insights/auto-generated',
    authRateLimiter,
    authMiddleware,
    asyncHandler(async (req, res) => {
      res.status(200).json(secondBrainService.getAutoGeneratedInsights(req.authUser!.userId));
    }),
  );

  return router;
};
